### ISSUE TITLE
move to bcgov GitHub?

### ISSUE THREAD

**Issue by stephhazlitt** [bcgov/drake-example#1]
This is great @boshek. I made a few edits so it runs on my MacBook, and prepped the repo for being "open". Is there any reason this should not be in bcgov-GitHub?

**Comment by NoushinN** [comment]
it's really nice! I had an issue with the graph not showing and realized there's a dependency for visNetwork library, sorry that I added to the function and not to a pull request...

**Comment by stephhazlitt** [comment]
I believe `drake` calls the package under the hood, but your machine does need pahntomjs to render the image. Try running `webshot::install_phantomjs()` and then running the script w/o the explicit `library(visNetwork)` call? This fix was in the error message for me when I hit the same issue. If it runs maybe remove the dependency?

**Comment by NoushinN** [comment]
It does run ok with webshot::install_phantomjs() without library(visNetwork)...does that make webshot::install_phantomjs() a dependency? or could add `need for webshot::install_phantomjs()` as a comment

**Comment by stephhazlitt** [comment]
I think it is only a Mac thing, where `phantomjs` is not pre-installed&mdash;which is why @boshek didn't have an issue when he authored the script with his Windows machine. You could, although users get that informative error and fix message in the console already?

**Comment by stephhazlitt** [comment]
@NoushinN Tx for offering these suggestions. 

Can I ask that you provide code suggestions via PR moving forward&mdash;makes it easier to have the discussion and let the maintainer decide what shape they want the repo to take. I have fixed the merge conflict from the push with your inserted comment. 

Let's "close" this discussion, but leave the issue open as it was meant to be a placeholder for a discussion abt where the repo should live.

**Comment by NoushinN** [comment]
@stephhazlitt thank you, note taken, sounds good.

**Comment by stephhazlitt** [comment]
Re-opening as the issue topic has not yet been discussed.

**Comment by boshek** [comment]
@NoushinN I would wholeheartedly agree with @stephhazlitt here. Take this issue for example which has been sidetracked. *Never be afraid to open a new issue*. That keeps topics siloed and avoid multi-threaded conversations like this one. I also agree about the need for pull requests. This is critical for a development. The equivalent would be going in and editing one of your word docs without any discussion or permissions.

Now on to the original thread question posed by @stephhazlitt:

Absolutely but I think I'd like this to mature a little here first. I haven't fully wrapped my head around the basics of drake and I'd be worried about providing poor advice. My sense is that as a team we use it, modify this repo (with PRs) and re-visit this conversation in a while.

**Comment by NoushinN** [comment]
@boshek sounds good, sorry for breaching the lines and mixing things up here, def. adding it to my pointers of GitHub collaboration etiquette

**Comment by boshek** [comment]
@ll911 Is there a path to move repos to the bcgov github? I'd like to move this repo there if possible.
Thanks!

**Comment by ll911** [comment]
@boshek please confirm no sensitive data in the repo, I will move the transfer the repo after your confirmation.

**Comment by boshek** [comment]
@ll911 no sensitive data

**Comment by ll911** [comment]
done.
